services:

  redmine-pusher:
    build:
      context: ./listen_and_repeat_bot/redmine_pusher
    restart: always
    init: true
    environment:
      PYTHONPATH: .
      TZ: ${TZ}
      POLL_CHANNELS_URL: ${POLL_CHANNELS_URL}
      REDMINE_ADDR: ${REDMINE_ADDR}
      REDMINE_API_KEY: ${REDMINE_API_KEY}
      MAX_DAYS: ${MAX_DAYS}
      LOGLEVEL: ${LOGLEVEL}
      POLL_INTERVAL: ${POLL_INTERVAL}
    networks:
      internal-network:

  telegram-poll-channels:
    build:
      context: ./listen_and_repeat_bot/poll_channels
    restart: always
    init: true
    environment:
      PYTHONPATH: .
      TZ: ${TZ}
      LISTEN_ADDRESS: ${LISTEN_ADDRESS}
      PHONE: ${PHONE}
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      SESSION_NAME: ${SESSION_NAME}
      LOGLEVEL: ${LOGLEVEL}
    volumes:
      - ./secrets/config.yml:/listen_and_repeat_bot/config.yml
      - ./secrets/listen_and_repeat.session:/listen_and_repeat_bot/listen_and_repeat.session
    networks:
      internal-network:


volumes:
  data-storage:

networks:
  internal-network: