name: Check code quality

on: 
  push:
    branches:
      - main

jobs:

  pylint-testing:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pipenv
      - run: pip install pipenv

      - name: install pylint
        run: |
          pipenv install --dev

      - name: check modules
        run: |
          pipenv run pylint ./listen_and_repeat_bot/redmine_pusher
          pipenv run pylint ./listen_and_repeat_bot/poll_channels
          pipenv run pylint ./session_handler