name: Check code quality

on: 
  push:
    branches:
      - main

jobs:

  pylint-testing:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pipenv
      - run: pip install pipenv

      - name: check poll_channels module
        working-directory: ./listen_and_repeat_bot/poll_channels
        continue-on-error: true
        run: |
          pipenv install --dev
          pipenv run pylint *.py

      - name: check redmine_pusher module
        working-directory: ./listen_and_repeat_bot/redmine_pusher
        continue-on-error: true
        run: |
          pipenv install --dev
          pipenv run pylint *.py

      - name: check session_handler module
        working-directory: ./
        continue-on-error: true
        run: |
          pipenv install --dev
          pipenv run pylint ./session_handler/*.py